# docker-compose.yml
version: '3.8'

services:
  analise-risco:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VALIDACAO_API_URL=http://validacao-dados:3001
      - SCORE_API_URL=http://score:3000
    depends_on:
      - redis
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - microservices-network

volumes:
  redis-data:

networks:
  microservices-network:
    driver: bridge